<?php
/**
 * Created by PhpStorm.
 * User: wuyongyu
 * Date: 2017/8/27
 * Time: 10:04
 */
 if (!defined('IN_ANWSION'))
 {
     die;
 }

 class main extends AWS_CONTROLLER
 {
     public function setup()
     {
         parent::setup(); // TODO: Change the autogenerated stub

         $this->crumb(AWS_APP::lang()->_t('视频播放'),'/video/');
     }


     public  function index_action()
     {

         TPL::output('/video/index');
     }
 }